% Even Fibonacci numbers
% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
% the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
% https://projecteuler.net/problem=2
% Author: Joao Henrique Machado Silva
% Email: joaoh82@gmail.com
% Github: https://github.com/joaoh82
-module(pe_problem2).
-export([fibonacci_sum_below/1]).

fibonacci_sum_below(Num_max) ->
    fibonacci(1, 2, 0, Num_max).

fibonacci(Num1, Num2, Sum, Max) when Num2 >= Max ->
    Sum;
fibonacci(Num1, Num2, Sum, Max) ->
    Num3 = Num1 + Num2,
    New_sum = sum(Num2, Sum),
    fibonacci(Num2, Num3, New_sum, Max).

sum(N, Sum) ->
    if
        (N rem 2 == 0) ->
            Sum + N;
        true -> Sum    
    end.

